//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EvaluationService : ICrudService<Evaluation>, IEvaluationService
{
	public virtual IValidatorService<Evaluation> Validator
	{
		get;
		set;
	}

	public virtual EvaluationRepository Repository
	{
		get;
		set;
	}

    public virtual void Create(Evaluation subject)
	{
		throw new System.NotImplementedException();
	}

    public virtual Evaluation Get(int id)
	{
		throw new System.NotImplementedException();
	}

    public virtual IEnumerable<Evaluation> GetAll()
	{
		throw new System.NotImplementedException();
	}

    public virtual void Delete(Evaluation subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(int id)
	{
		throw new System.NotImplementedException();
	}

    public virtual void Update(Evaluation subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddEvaluation(int studentId, Byte grade, int projectId, int skillId)
	{
		throw new System.NotImplementedException();
	}

}

