//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BarometerDomain.Repositories;
using BarometerStudent.Services.Validation;

public class GroupService : IGroupService, ICrudService<Group>
{
	public virtual IValidationService<Group> Validater
	{
		get;
		set;
	}

	public virtual GroupRepository Repository
	{
		get;
		set;
	}

	public virtual void AddStudent(int groupId, int studentId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveStudent(int groupId, int studentId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Create(Group subject)
	{
		throw new System.NotImplementedException();
	}

    public virtual Group Get(int id)
	{
		throw new System.NotImplementedException();
	}

    public virtual IEnumerable<Group> GetAll()
	{
		throw new System.NotImplementedException();
	}

    public virtual void Delete(Group subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(int id)
	{
		throw new System.NotImplementedException();
	}

    public virtual void Update(Group subject)
	{
		throw new System.NotImplementedException();
	}

}

