//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GroupService : IGroupService, ICrudService
{
	public virtual AKD::IValidationService<Group> Validater
	{
		get;
		set;
	}

	public virtual GroupRepository Repository
	{
		get;
		set;
	}

	public virtual void AddStudent(int groupId, int studentId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void RemoveStudent(int groupId, int studentId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Create(T subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual T Get(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<T> GetAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(T subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update(T subject)
	{
		throw new System.NotImplementedException();
	}

}

