//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProjectService : ICrudService, IProjectService
{
	public virtual IValidatorService<Project> Validator
	{
		get;
		set;
	}

	public virtual ProjectRepository Repository
	{
		get;
		set;
	}

	public virtual void Create(T subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual T Get(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<T> GetAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(T subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update(T subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddTutor(int userId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddGroup(int groudId)
	{
		throw new System.NotImplementedException();
	}

}

