//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using BarometerDomain.Repositories;
using BarometerStudent.Services.Validation;

public class ProjectService : ICrudService<Project>, IProjectService
{
	public virtual IValidationService<Project> Validator
	{
		get;
		set;
	}

	public virtual ProjectRepository Repository
	{
		get;
		set;
	}

	public virtual void Create(Project subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual Project Get(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual IEnumerable<Project> GetAll()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(Project subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Delete(int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Update(Project subject)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddTutor(int userId)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddGroup(int groudId)
	{
		throw new System.NotImplementedException();
	}

}

