//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Group
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual User Tutor
	{
		get;
		set;
	}

	public virtual IEnumerable<Student> Student
	{
		get;
		set;
	}

	public virtual IEnumerable<Project> Project
	{
		get;
		set;
	}

}

