//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Project
{
	public virtual string Name
	{
		get;
		set;
	}

	public virtual string Description
	{
		get;
		set;
	}

	public virtual bool Anonymous
	{
		get;
		set;
	}

	public virtual IEnumerable<ProjectPeriod> ProjectPeriod
	{
		get;
		set;
	}

	public virtual IEnumerable<Skill> Skill
	{
		get;
		set;
	}

	public virtual User Project docent
	{
		get;
		set;
	}

}

