//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ProjectPeriod
{
	public virtual Date Start
	{
		get;
		set;
	}

	public virtual Date End
	{
		get;
		set;
	}

	public virtual IEnumerable<Evaluation> Evaluation
	{
		get;
		set;
	}

}

