//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User
{
	public virtual string Login
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual IEnumerable<RoleType> RoleType
	{
		get;
		set;
	}

	public virtual Student Student
	{
		get;
		set;
	}

}

