//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class EvaluationController : Controller, IModifyAction, IStudentAction
{
    /*
	public  void Evaluate(int ProjectId)
	{
		to do
	}

	public  void Student(int StudentNr)
	{
		to do
	}
     */

}

