//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class StudentController : Controller, ICrudAction, IProgressAction
{
    /*
	public  void Create(ViewModel model)
	{
		to do
	}

	public  void Delete(int int id)
	{
		to do
	}

	public  void Update(int int id, object ViewModel)
	{
		to do
	}

	public  void Overview()
	{
		to do
	}

	public  void Read(int Int id)
	{
		to do
	}

	public  void Progress(int id)
	{
		to do
	}
     */

}

