//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BarometerDomain.Model
{
    public class Group : IEntity
    {
        public Group()
        {
            Student = new List<Student>();
            Project = new List<Project>();
        }
        public int Id { get; set; }
        public string Name
        {
            get;
            set;
        }

        public virtual User Tutor
        {
            get;
            set;
        }

        public virtual ICollection<Student> Student
        {
            get;
            set;
        }

        public virtual ICollection<Project> Project
        {
            get;
            set;
        }

    }
}
