//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace BarometerDomain.Model
{
    public class ProjectPeriod : IEntity
    {
        public ProjectPeriod()
        {
            Evaluation = new List<Evaluation>();
        }
        public int Id { get; set; }
        [Required]
        public string Name
        { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "Dit veld is verplicht.")]
        [Display(Name = "Start datum: ")]
        public DateTime Start
        {
            get;
            set;
        }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "Dit veld is verplicht.")]
        [Display(Name = "Eind datum: ")]
        public DateTime End
        {
            get;
            set;
        }

        public virtual IList<Evaluation> Evaluation
        {
            get;
            set;
        }

    }
}
