//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace BarometerDomain.Model
{
    public class ProjectPeriod : IEntity
    {
        public ProjectPeriod()
        {
            Evaluation = new List<Evaluation>();
        }
        public int Id { get; set; }
        [Required]
        public DateTime Start
        {
            get;
            set;
        }
        [Required]
        public DateTime End
        {
            get;
            set;
        }

        public ICollection<Evaluation> Evaluation
        {
            get;
            set;
        }

    }
}
