//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

public class Project : IEntety
{
    public int Id { get; set; }
    [Required]
	public string Name
	{
		get;
		set;
	}
    [Required]
	public string Description
	{
		get;
		set;
	}
    [Required]
	public bool Anonymous
	{
		get;
		set;
	}
    
	public IEnumerable<ProjectPeriod> ProjectPeriod
	{
		get;
		set;
	}

	public IEnumerable<Skill> Skill
	{
		get;
		set;
	}

	public User ProjectDocent
	{
		get;
		set;
	}

}

