//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace BarometerDomain.Model
{
    public class Skill : IEntity
    {
        public int Id { get; set; }
        [Required]
        public string Category
        {
            get;
            set;
        }

        public virtual IList<Project> Projects { get; set; }

    }
}
