//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace BarometerDomain.Model
{
    public class Student : User
    {

        public Student()
            : base()
        {
            Project = new List<Project>();
        }
        [Required]
        public int Number
        {
            get;
            set;
        }

        public virtual IList<Project> Project
        {
            get;
            set;
        }

    }
}
