//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;

namespace BarometerDomain.Model
{
    public class User : IEntity
    {
        public User()
        {
            RoleType = new List<RoleType>();
            MentorStudent = new List<Student>();
        }
        public virtual int Id { get; set; }
        public string Login
        {
            get;
            set;
        }

        [Required]
        public string Name
        {
            get;
            set;
        }

        [Required]
        public virtual IList<RoleType> RoleType
        {
            get;
            set;
        }

        public virtual IList<Student> MentorStudent
        {
            get;
            set;
        }
    }
}
